library(MASS)
mydata<-airquality
View(mydata)
head(mydata)
tail(mydata)
head(mydata,8)
tail(mydata,9)
summary(mydata)
mean(mydata$Ozone)
mean(mydata$Solar.R)
mean(mydata$Temp)
mean(mydata$Ozone,na.rm = T)
sd(mydata$Temp)
sd(mydata$Ozone,na.rm = T)
library(psych)
describe(mydata)

cor(mydata$Wind,mydata$Temp)
cor(mydata$Ozone,mydata$Solar.R,use="complete.obs")
cor(mydata,use="complete.obs")
summary(iris)
hist(iris$Sepal.Width)
hist(iris$Sepal.Width,col = "orange")
#corrected
hist(iris$Sepal.Length,col="red",xlab="sepal withh",ylab="ysapal",main="saple with width")

boxplot(iris$Sepal.Length,horizontal=T,col = "light blue")
boxplot(iris$Sepal.Length,iris$Sepal.Width,horizontal=T)
summary(iris)
boxplot(iris$Sepal.Length,iris$Sepal.Species)
barplot(table(iris$Species),col="orange") #can ad horizontal=T
table(iris$Species)
prop.table(table(iris$Species))
barplot(prop.table(table(iris$Species)))
install.packages(RColorBrewer)
library(RColorBrewer)
display.brewer.all()
hist(iris$Sepal.Width,col=brewer.pal(8,"Set3"))
